### ISSUE TITLE
RFE: please update for latest `sphinx-autodoc-typehints` 1.18.1

### ISSUE THREAD

**Issue by kloczek** [sphinx-toolbox/sphinx-toolbox#108]
https://github.com/sphinx-toolbox/sphinx-toolbox/blob/1f8d48a7330695934ee6a7cba6467c549d343b5f/requirements.txt#L12

**Comment by kloczek** [comment]
gentle ping ..

**Comment by btjanaka** [comment]
We are encountering the same issue on https://github.com/icaros-usc/pyribs/pull/201

**Comment by btjanaka** [comment]
I just saw this was fixed. Thank you so much!

**Comment by itsdawei** [comment]
@kloczek I was using Sphinx 4.5.0 and everything works fine. The problem with using Sphinx 5+ is that its too recent so many extensions have not yet adapted to it yet.

**Comment by kloczek** [comment]
Nevertheless it would be good to make `sphinx-toolbox` sphinx 5.x ready ..

**Comment by kloczek** [comment]
Could you plese at least confirm thart you are able reproduce the issue with sphinx 5?
I've disabled for now in my build procedure build documentsation so I'm not asking fix that as JFDIN .. take your time😋

**Comment by 1kastner** [comment]
@kloczek see https://github.com/sphinx-toolbox/sphinx-toolbox/pull/120 :-)

**Comment by kloczek** [comment]
With 3.2.0 already released looks like this ticket can be closed now.
