### ISSUE TITLE
Allow support docutils==0.18

### ISSUE THREAD

**Issue by jorgepiloto** [sphinx-toolbox/sphinx-toolbox#117]
🐞 **Problem**
When using the latest Sphinx version and some modern extensions, the following dependency conflict shows up:

```text
The conflict is caused by:
    The user requested docutils==0.18.1
    sphinx 5.1.1 depends on docutils<0.20 and >=0.14
    sphinx-tabs 3.4.1 depends on docutils~=0.18.0
    sphinx-toolbox 3.1.2 depends on docutils<0.18 and >=0.16
```

There is a new version of [docutils==0.19.0](https://pypi.org/project/docutils/0.19/). If possible, it would be nice for sphinx-toolbox to support `docutils==0.18.0`.

**Comment by 1kastner** [comment]
@jorgepiloto see https://github.com/sphinx-toolbox/sphinx-toolbox/pull/120 :-)

**Comment by jorgepiloto** [comment]
Thanks for pinging, @1kastner. Closing this as it was solved in https://github.com/sphinx-toolbox/sphinx-toolbox/pull/120
