### ISSUE TITLE
Could not import extension sphinx_toolbox.more_autodoc.autonamedtuple

### ISSUE THREAD

**Issue by 1kastner** [sphinx-toolbox/sphinx-toolbox#119]
## Description
When building my docs, they fail with the message `Could not import extension sphinx_toolbox.more_autodoc.autonamedtuple (exception: cannot import name 'RemovedInSphinx50Warning' from 'sphinx.deprecation' (/home/runner/.local/lib/python3.10/site-packages/sphinx/deprecation.py))`.

## Steps to Reproduce

Run cd ./docs/ && make html SPHINXOPTS="-W --keep-going", see, e.g., https://github.com/1kastner/conflowgen/runs/7601083543?check_suite_focus=true for reference.

## Expected result:

At this stage, this faulty import should not happen I guess?

## Reproduces how often:

Every time.

## Version

  * Operating System: Linux
  * Python: 3.8, 3.10
  * sphinx-toolbox: 3.1.2 (newest version is installed in pipeline, currently no fixed version)
  * sphinx: 5.1.1 (newest version is installed in pipeline, currently no fixed version)

## Installation source
pip

**Comment by Sharpz7** [comment]
I have this issue now to, and didn't seem to have it before the 27th of July, which is strange

**Comment by 1kastner** [comment]
Well, a new sphinx version is out. I downgraded Sphinx to avoid this issue for the meantime

**Comment by domdfcoding** [comment]
This and a few other issues should be resolved by #120. Can you test with [v3.2.0b1](https://pypi.org/project/sphinx-toolbox/3.2.0b1/)?

**Comment by 1kastner** [comment]
The solution works for me, thank you very much for the quick fix!
