### ISSUE TITLE
autonamedtuple leaves (constructor?) parameters blank

### ISSUE THREAD

**Issue by 1kastner** [sphinx-toolbox/sphinx-toolbox#121]
## Description

I have a NamedTuple I want to document. However, the parameters remain empty but are shown. This happens because of  `autodoc_typehints = 'both'` I guess.

## Steps to Reproduce

Have a NamedTuple like this:
```
class A(NamedTuple):

    #: abc
    def: float

    #: xyz
    ghi: float
```

## Actual result:

One example:

![grafik](https://user-images.githubusercontent.com/5236165/182648618-b0fe456b-5303-4183-a2b7-d8f247a2f662.png)

## Expected result:

Either, the parameters could also be documented, just like the enum values, or they should be hidden. While a NamedTuple technically has a constructor, this is nothing to explicitely document and discuss in the docs.

## Reproduces how often:

always

## Version

  * Operating System:
  * Python: 3.9
  * sphinx-toolbox: current

## Installation source
pip

**Comment by domdfcoding** [comment]
Is this with Sphinx 5.x? if so does the problem persist with sphinx-toolbox 3.2.0b1?

**Comment by 1kastner** [comment]
Yes, it does. For the exact versions:

```
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphinx_toolbox
>>> sphinx_toolbox.__version__
'3.2.0b1'
>>> import sphinx
>>> sphinx.__version__
'5.1.1'
>>>
```

I just re-ran the documentation building to be sure and the parameters are still there.

**Comment by domdfcoding** [comment]
Above the bit you took the screenshot of, where it says "Parameters:", are they duplicated but with the title "Fields"? Like this:

![image](https://user-images.githubusercontent.com/8050853/183749501-b31c94fd-dfed-473d-8319-72fc04d39dad.png)

If so can you try the [fix-121 branch](https://github.com/sphinx-toolbox/sphinx-toolbox/tree/fix-121)?

**Comment by 1kastner** [comment]
Exactly, the parameters are a duplicate of the fields, just without the documentation of it. I will try the branch shortly.

**Comment by 1kastner** [comment]
It solved the issue perfectly, thank you very much!
