### ISSUE TITLE
`|nbsp|` appearing for the `.. autonamedtuple::` directive resulting documentation

### ISSUE THREAD

**Issue by engineerjoe440** [sphinx-toolbox/sphinx-toolbox#136]
## Description

I just started using the `.. autonamedtuple::` directive to begin formatting the namedtuples in some of my projects. And they look great aside from the peculiar `|nbsp|` appearing between the field index and its short description.

## Steps to Reproduce

   1. Implement a `collections.namedtuple` in source that you would like to document.
   2. Configure Sphinx documentation to use `.. autonamedtuple::` for the value.
   3. Build documentation and verify that `|nbsp|` is used to separate the field index and brief description.

## Actual result:

![image](https://user-images.githubusercontent.com/33275230/212492001-97d368c6-e7a2-4bc7-9943-80918aa00280.png)

## Expected result:

I would have expected something like a paragraph symbol used in place of the `nbsp` here.
![image](https://user-images.githubusercontent.com/33275230/212493306-98b18a42-e40e-45c8-9488-4efc1d996268.png)

## Reproduces how often:

Standard behavior -- appears every time Sphinx is built.

## Version

  * Operating System: Windows 11
  * Python: 3.11.1
  * sphinx-toolbox: 3.3.0

## Installation source
- PyPI

## Other Additional Information:

I've identified this as coming from [line 401 in `sphinx_toolbox/more_autodoc/autonamedtuple.py`](https://github.com/sphinx-toolbox/sphinx-toolbox/blob/master/sphinx_toolbox/more_autodoc/autonamedtuple.py#L401). It seems like this was perhaps a placeholder, or just a location that Sphinx was intended to swap in an HTML `&nbsp` character? I would like to suggest that the characters `nbsp` be replaced with the appropriate content to format a paragraph symbol such as the following:

![image](https://user-images.githubusercontent.com/33275230/212493306-98b18a42-e40e-45c8-9488-4efc1d996268.png)

Thank you so much! I think this is marvelous to have such additional tooling for the Sphinx ecosystem. I desirable, I would be willing to investigate contributing a change to modify `nbsp` --> `<paragraph symbol>` myself.

**Comment by domdfcoding** [comment]
I haven't been able to reproduce this myself. Can you post a copy of your `conf.py` file?

Sphinx is supposed to substitute `|nbsp|` for an actual non-breaking space, but for some reason that's not happening.

**Comment by engineerjoe440** [comment]
Sure! Here's the `conf.py`

```python
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os
import sys
import getpass

BASE_PATH = os.path.dirname(os.path.abspath(__file__))


# -- Project information -----------------------------------------------------

project = 'SEL AcSELerator RTAC Python CLI Wrapper'
copyright = '2023, Schweitzer Engineering Laboratories'
author = 'Schweitzer Engineering Laboratories'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [ 
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'numpydoc',
    'sphinxcontrib.confluencebuilder',
    'sphinxarg.ext',
    'myst_parser',
    'sphinx_toolbox.more_autodoc.autonamedtuple',
    #'sphinx_docbook.docbook_builder',
]
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_material_sel'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

#html_logo = os.path.join(BASE_PATH, 'SELImage.png')
html_favicon = os.path.join(BASE_PATH, 'selfavicon.png')
html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "searchbox.html"]
}

# Material theme options (see theme.conf for more information)
html_theme_options = {

    # Set the name of the project to appear in the navigation.
    'nav_title': '  ',

    # Specify a base_url used to generate sitemap.xml. If not
    # specified, then no sitemap will be built.
    'base_url': 'https://selinc.com/',

    # Specify that the Icon Should use a generic git logo
    'repo_type': "git",

    # Set the color and the accent color
    'color_primary': 'blue',
    'color_accent': 'light-blue',

    # Set the leading text at the top of the index page and others
    "heroes": {
        "index": "<b><i>Python Bindings for the AcSELerator RTAC CLI</i></b>",
    },

    # Visible levels of the global TOC; -1 means unlimited
    'globaltoc_depth': 2,
    # If False, expand all TOC entries
    'globaltoc_collapse': True,
    # If True, show hidden TOC entries
    'globaltoc_includehidden': False,
}

# END
```

**Comment by domdfcoding** [comment]
I see you have the `myst_parser` extension enabled. Is the `.. autonamedtuple::` directive in a markdown file?

**Comment by engineerjoe440** [comment]
> I see you have the `myst_parser` extension enabled. Is the `.. autonamedtuple::` directive in a markdown file?

Yes, the `.. autonamedtuple::` appears in a markdown file as such:
![image](https://user-images.githubusercontent.com/33275230/213259652-5075d19f-224c-4b29-b96f-855916f2b70d.png)

**Comment by domdfcoding** [comment]
I think I've found the problem, then. The `|nbsp| substitution to an actual no-break space seems to be reST specific so isn't happening in markdown. 

Can you try installing the `fix-nbsp` branch (put `git+https://github.com/sphinx-toolbox/sphinx-toolbox@fix-nbsp` in your requirements instead of `sphinx-toolbox`)?

I've done away with the substitution altogether and just put the unicode character in directly.

**Comment by engineerjoe440** [comment]
That looks marvelous!!!

![image](https://user-images.githubusercontent.com/33275230/213527694-d9ea848d-165f-4da8-974e-114563b9d8bd.png)
