### ISSUE TITLE
[FEATURE] Support for Sphinx 4

### ISSUE THREAD

**Issue by takos22** [sphinx-toolbox/sphinx-toolbox#68]
I use Sphinx 4 in my project and I wanted to use this extension but it doesn't officially support Sphinx 4. On installation, it uninstalled Sphinx 4 in favor of Sphinx 3.5.4. Could you please update the Sphinx requirement?

https://github.com/sphinx-toolbox/sphinx-toolbox/blob/aff5e5595c5dda13012253e55dec6d9aec611197/requirements.txt#L11

**Comment by takos22** [comment]
I tested the extension with Sphinx 4 for a bit, and I found that `get_doc` was updated: ``get_doc() takes from 1 to 2 positional arguments but 3 were given``

**Comment by domdfcoding** [comment]
Hi @takos22 

I have released version [2.14.0](https://github.com/sphinx-toolbox/sphinx-toolbox/releases/tag/v2.14.0) with support for Sphinx 4.0. 
A version with support for Sphinx 4.1 should be out soon, but there's a little more work required.

**Comment by 1kastner** [comment]
A very similar issue exists now with Sphinx 4.4 and apeye - see https://github.com/domdfcoding/enum_tools/issues/54 for more details on the error. I first tried to update Sphinx from 4.3 to 4.4 but it automatically downgraded to 4.3 not to break things on readthedocs.

**Comment by 1kastner** [comment]
It looks like https://github.com/sphinx-toolbox/sphinx-toolbox/commit/94400b8d92a4fdc02c7deaabee55db390f3e33ed fided it in this case.

I am not the original author of this issue but I guess it can be closed now.
