### ISSUE TITLE
Styling lost with jupyter-book and automodule/autonamedtuple

### ISSUE THREAD

**Issue by StigKorsnes** [sphinx-toolbox/sphinx-toolbox#79]
Hi!
Writing some documentation using jupyter-book, I decided to use this package for better looking api documention. (using sphinx ext.autodoc). However, some styling was lost when using autonamedtuple. The same applies for other packages like enum_tools , and pydantic models with autodoc_pydantic. However, authors of autodoc_pydantic was able to fix this by using sphinx events to add missing css classes. I.e "py namedtuple" does not render ok, but "py class namedtuple" does.

Please see [JB](https://github.com/executablebooks/jupyter-book/issues/1563) for the issue, and [autodoc_pydantic](https://github.com/mansenfranzen/autodoc_pydantic/issues/77) . Would you be willing to implement such a fix? Currently I do a post documentation build step, where I add "class" to all html elements with "py namedtuple".

**Comment by StigKorsnes** [comment]
@domdfcoding 
Using poetry poetry add -D git+https://github.com/sphinx-toolbox/sphinx-toolbox
 • Updating sphinx-toolbox (2.15.1 -> 2.16.0b1 33b03b0)

No issues here, looks as expected :)

**Comment by domdfcoding** [comment]
Great. I'll make a release now.

**Comment by StigKorsnes** [comment]
Thanks for fixing this!
